### ISSUE TITLE
should declare which AWS region to use

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/UsingAwsSdkInKatalonStudio#4]
I tried to run https://github.com/kazurayam/UsingAwsSdkInKatalonStudio/blob/0.3/Scripts/ListMyS3Buckets/Script1545180936915.groovy and got the following error

```
2023-04-28 09:43:37.650 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/ListMyS3Buckets FAILED.
Reason:
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.client.builder.AwsSyncClientBuilder$build.call(Unknown Source)
	at ListMyS3Buckets.run(ListMyS3Buckets:11)
```

Should express which AWS region to use
```
final AmazonS3 s3 = AmazonS3ClientBuilder.standard()
						.withRegion("ap-northeast-1")
						.build();

```

**Comment by kazurayam** [comment]
done at v0.4
